# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{css-sprites}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ayose (setepo)", "Morgan Chrisitansson"]
  s.date = %q{2009-09-17}
  s.description = %q{The first step is generate the index:

    $ rake css_sprites:update
This will find all the images and make a bundle with them. Animated images (like GIF or APNG with two or more frames) are always excluded.

The plugin will create one image per format (a file with JPEG images, another file with PNGs, ...).

And that is all.}
  s.email = %q{code@mog.se}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "css-sprites.gemspec",
     "init.rb",
     "install.rb",
     "lib/css_sprites.rb",
     "lib/css_sprites/generator.rb",
     "lib/css_sprites/view_methods.rb",
     "lib/tasks/css_sprites.rake",
     "lib/tasks/css_sprites.rb",
     "templates/blank.gif",
     "templates/css-sprites.yml",
     "test/css_sprites_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/morganchristiansson/css-sprites}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Rails plugin for generate CSS sprites}
  s.test_files = [
    "test/css_sprites_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
